### ISSUE TITLE
install_requires vs requirements files

### ISSUE THREAD

**Issue by pvnieo** [mCodingLLC/SlapThatLikeButton-TestingStarterProject#1]
Hi,

Thanks for the repo.

I have a question regarding the `setup.cfg` and `requirements.txt` files. Actually, it seems that you define the dependencies in both files, but only the dependencies defined in `setup.cfg` will be used during installation. What is the point of creating `requirements.txt`.

Thank you in advance.

**Comment by mCodingLLC** [comment]
Sure thing! You can read a full discussion about the difference in purposes between requirements.txt and setup.{cfg,py} requirements here: https://stackoverflow.com/questions/43658870/requirements-txt-vs-setup-py.

Basically, requirements.txt is for setting up a **reproducible** environment, either for development purposes or deployment purposes, whereas setup.cfg lists more **abstract** dependencies. 

Think about it like this: if I want to deploy an application to 100 servers, I want every server to be exactly the same as the environment I did my tests in, so I install the requirements.txt to get exact versions of all my dependencies installed. However, I don't want to require these exact versions of things from my project in _someone else's_ project because there may be conflicts with versions that they use, so setup.cfg has the more abstract list of **acceptable** versions, which is broader than the ones I personally develop and deploy with. Their project can have it's own requirements.txt with exact versions of all their dependencies (recursively including all my dependencies), so that they too can deploy their project in a reproducible environment that's the same as the one where they run their tests, even though the exact versions they are using are different than mine.

**Comment by pvnieo** [comment]
Thanks for the quick response, this answer my question :pray:
